Show_Icon_Red = ''
Show_Icon_Green = ''
From_Date = ''
Total = 0
Duplicate = 0
Expired = 0
Inserted = 0
Skipped = 0
Deadline = 0
Qc_Tenders = 0
html_string = "".replace(',,', ' , ')

HTML_File_String = ''

ncb_icb = ''
search_id = ''
cpv_userid = ''
dms_entrynotice_tblquality_status = ''
quality_id = ''
Col1 = ''
Col2 = ''  # For India Only Other Wise Blank
Col3 = ''
Col4 = ''
Col5 = ''
dms_downloadfiles_tbluser_id = ''
selector_id = ''
dms_downloadfiles_tbldatatype = ''
dms_entrynotice_tblnotice_type = ''
Country = ''
